spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SecKill?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 785099FFDD3F13D1ACEC7CBA98232021475759CE3AA9EFBF90CDD0E0
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      auto-commit: true
      connection-test-query: SELECT 1

  devtools:
    restart:
      enabled: true
  redis:
    host: 127.0.0.1   #服务器地址 你服务器或本机地址
    port: 6379           #连接端口
    database: 0          #数据库索引，默认0
    password: 123456     #密码
    jedis:
      pool:
        max-active: 8    #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1     #最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 8      #最大空闲连接数
        min-idle: 0      #最小空闲连接数
    timeout: 5000        #连接超时时间（毫秒）
