spring:
  application:
    name: service_edu
    # 项目在启动的时候根据下面的配置去寻找配置文件
  cloud:
    nacos:
      config:
        server-addr: localhost:8848 # 配置文件的地址
        file-extension: yml # 文件类型



  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_video_learning_system_db?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 785099FFDD3F13D1ACEC7CBA98232021475759CE3AA9EFBF90CDD0E0
    hikari:
      pool-name: DateHikariCP
      minimum-idle: 5
      idle-timeout: 180000
      auto-commit: true
      connection-test-query: SELECT 1
  #开启热加载
  devtools:
    livereload:
      port: 35779
    restart:
      additional-paths: src/main/java
      exclude: WEB-INF/**,static/**,public/**,application-dev.properties
      enabled: true
  #配置Redis相关信息
  redis:
    host: 127.0.0.1   #服务器地址 你服务器或本机地址
    port: 6379           #连接端口
    database: 0          #数据库索引，默认0
    password: 123456     #密码
    jedis:
      pool:
        max-active: 8    #连接池最大连接数(使用负值表示没有限制)
        max-wait: -1     #最大阻塞等待时间(使用负值表示没有限制)
        max-idle: 8      #最大空闲连接数
        min-idle: 0      #最小空闲连接数
    timeout: 5000        #连接超时时间（毫秒）

  #文件存储配置(本地)
  file-storage: #文件存储配置
    thumbnail-suffix: ".min.jpg" #缩略图后缀，例如【.min.jpg】【.png】
    aliyun-oss: # 阿里云 OSS ，不使用的情况下可以不写
      - platform: aliyun-oss-1 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: LTAI5tDA1Ud51HRmc62j2mMm
        secret-key: 2j4PIY8uQ7WEatCOPMZYbhqtBcnzS1
        end-point: oss-cn-nanjing.aliyuncs.com
        bucket-name: keyle777
        domain: https://keyle777.oss-cn-nanjing.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: image/ # 基础路径

      - platform: aliyun-oss-2 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: LTAI5tDA1Ud51HRmc62j2mMm
        secret-key: 2j4PIY8uQ7WEatCOPMZYbhqtBcnzS1
        end-point: oss-cn-nanjing.aliyuncs.com
        bucket-name: keyle777
        domain: https://keyle777.oss-cn-nanjing.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: subject/ # 基础路径

      - platform: aliyun-oss-3 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: LTAI5tDA1Ud51HRmc62j2mMm
        secret-key: 2j4PIY8uQ7WEatCOPMZYbhqtBcnzS1
        end-point: oss-cn-nanjing.aliyuncs.com
        bucket-name: keyle777
        domain: https://keyle777.oss-cn-nanjing.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: cover/ # 基础路径

      - platform: aliyun-oss-4 # 存储平台标识
        enable-storage: true  # 启用存储
        access-key: LTAI5tDA1Ud51HRmc62j2mMm
        secret-key: 2j4PIY8uQ7WEatCOPMZYbhqtBcnzS1
        end-point: oss-cn-nanjing.aliyuncs.com
        bucket-name: keyle777
        domain: https://keyle777.oss-cn-nanjing.aliyuncs.com/ # 访问域名，注意“/”结尾，例如：https://abc.oss-cn-shanghai.aliyuncs.com/
        base-path: video/ # 基础路径
    default-platform: aliyun-oss-1

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      # nacos服务地址



  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致
server:
  port: 8080




